In [81]:
import tensorflow as tf
import pandas as pd



In [82]:
A = tf.Variable([[5, 10, 15], [10, 20, 30], [100, 150, 200]])
A 


<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[  5,  10,  15],
       [ 10,  20,  30],
       [100, 150, 200]], dtype=int32)>

In [83]:
B = tf.Variable([[1, 0, -1], [2, 0, -2], [1, 0, -1]])
B

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 1,  0, -1],
       [ 2,  0, -2],
       [ 1,  0, -1]], dtype=int32)>

In [84]:
mult_out = tf.math.multiply(A, B)
mult_out


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[   5,    0,  -15],
       [  20,    0,  -60],
       [ 100,    0, -200]], dtype=int32)>

In [85]:
conv_out = tf.math.reduce_sum(mult_out)
conv_out


<tf.Tensor: shape=(), dtype=int32, numpy=-150>

# **Activity**

In [86]:
A = [[5, 10,15],
       [10,20,30],
       [100,150,200]]

B = [[1,0,-1],[2,0,-2],[1,0,-1]]

In [87]:
def multiple(A,B):
    result = [[0 for x in range(3)] for y in range(3)]
    for i in range(len(A)):
        for j in range(len(B)):
            result[i][j]=A[i][j]*B[i][j]
    return result

res = multiple(A,B)
res

[[5, 0, -15], [20, 0, -60], [100, 0, -200]]

In [88]:
grandtotal = 0
for row in res:
    total = 0
    for i in row:
        total += i
    
    grandtotal += total
print(grandtotal)

-150
